<?php
namespace portpontrieuxBundle\Repository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**

 * EmplacementRepository

 *

 * This class was generated by the Doctrine ORM. Add your own custom

 * repository methods below.

 */

class EmplacementRepository extends \Doctrine\ORM\EntityRepository
{
            public function mesEmplacementsQueryBuilder($page, $nbParPage)
            {
                        $queryBuilder = $this->createQueryBuilder('f');
                        // On récupère la Query à partir du QueryBuilder
                        $query = $queryBuilder->getQuery();
                        // On n'ajoute pas de critère ou tri particulier ici car on veut toutes les formations, la construction de notre requête est donc finie                    
                        // On gère ensuite la pagination grace au service Paginator qui nous fournit
                        // entre autres les méthodes setFirstResult et setMaxResults
                        $query
                          // On définit l'emplacement à partir duqel commencer la liste
                          ->setFirstResult(($page-1) * $nbParPage)
                          // Ainsi que le nombre de formations à afficher sur une page
                          ->setMaxResults($nbParPage)
                        ;   
                        // Enfin, on retourne l'objet Paginator correspondant à la requête construite
                        // (=>Ne pas oublier le "use Doctrine\ORM\Tools\Pagination\Paginator;" correspondant en début de fichier)
                        return new Paginator($query, true);

            }

}

